// THIS FILE WAS GENERATED BY TOOLING. DO NOT EDIT THIS FILE DIRECTLY.
import { PostMetaData } from './post-metadata';

export const postMetaData: PostMetaData[] = [
  {
    date: '2022-06-01T23:12:00.000Z',
    title: 'Why are there _nghost attributes all over my HTML?',
    tags: ['Angular', 'angular', 'nghost', '_nghost'],
    description: 'Why are there _nghost attributes all over my HTML?',
    slug: 'nghost',
    sectionNames: ['page-1.md'],
    summary:
      "Ever wonder what those strange `_nghost` and `_ngcontent` attributes are on your HTML tags?\n\nIf this doesn't sound familiar, go to any Angular app and open the developer console for your browser. Inspect the HTML source of the application and you will likely see `_nghost` and `_ngcontent` attributes on some DOM elements.",
  },
  {
    date: '2022-05-31T23:12:00.000Z',
    title: 'Directive Context',
    tags: ['Angular', 'angular', 'angular directive', 'context', 'directive'],
    description: 'What is a directive context in Angular?',
    slug: 'directive-context',
    sectionNames: ['page-1.md'],
    summary:
      'You may recognize the usage of `let isFirst = first` in the following template\n\n```html\n<div *ngFor="let event of eventQueue; let isFirst = first">\n    ...\n</div>\n```\n',
  },
];
