// THIS FILE WAS GENERATED BY TOOLING. DO NOT EDIT THIS FILE DIRECTLY.

import {
  Component,
  NgModule,
  Inject,
  PLATFORM_ID,
  OnInit,
  OnDestroy,
} from '@angular/core';
import { RouterModule } from '@angular/router';
import { CommonModule } from '@angular/common';
import { Meta } from '@angular/platform-browser';

import { CodeBlockComponent } from '../components-for-generated-routes/code-block/code-block.component';
import { CodeTabsComponent } from '../components-for-generated-routes/code-tabs/code-tabs.component';
import { DirectiveContextDemoComponent } from '../components-for-generated-routes/directive-context-demo/directive-context-demo.component';
import { HelloWorldComponent } from '../components-for-generated-routes/hello-world/hello-world.component';

@Component({
  selector: 'blog-angular-components-in-markdown',
  template: `
    <h1>Angular Components in Markdown</h1>
    <code-tabs>
      <ol code-headers>
        <li>page.md (this page)</li>
        <li>code-tabs.component.ts</li>
        <li>code-block.component.ts</li>
        <li>hello-world.component.ts</li>
        <li>Preview</li>
      </ol>
      <ol tabs>
        <li>
          <code-block
            slug="angular-components-in-markdown"
            src="page-as-markdown.md"
          >
          </code-block>
        </li>
        <li>
          <code-block
            slug="angular-components-in-markdown"
            src="code-tabs-component.md"
          >
          </code-block>
        </li>
        <li>
          <code-block
            slug="angular-components-in-markdown"
            src="code-block-component.md"
          >
          </code-block>
        </li>
        <li>
          <code-block
            slug="angular-components-in-markdown"
            src="hello-world-component.md"
          >
          </code-block>
        </li>
        <li>
          <hello-world> Some text to project </hello-world>
        </li>
      </ol>
    </code-tabs>
  `,
  styles: [
    `
      :host {
        display: block;
        max-width: 800px;
        margin: 2rem auto 0;

        @media screen and (max-width: 801px) {
          max-width: calc(100% - 24px);
        }
      }
    `,
  ],
})
export class AngularComponentsInMarkdownComponent implements OnInit, OnDestroy {
  constructor(
    @Inject(PLATFORM_ID) public platformId: Object,
    private meta: Meta
  ) {}

  ngOnInit(): void {
    this.meta.addTag({
      property: 'og:title',
      content: 'Angular Components in Markdown',
    });
    this.meta.addTag({ property: 'og:type', content: 'article' });
    this.meta.addTag({
      property: 'og:url',
      content:
        'https://aleksanderbodurri-eefbe.web.app/posts/angular-components-in-markdown',
    });
    this.meta.addTag({
      property: 'og:image',
      content: 'http://aleksanderbodurri-eefbe.web.app/assets/me.png',
    });
    this.meta.addTag({
      property: 'og:image:secure_url',
      content: 'https://aleksanderbodurri-eefbe.web.app/assets/me.png',
    });

    if (true) {
      this.meta.addTag({
        name: 'description',
        content:
          'Examples of some of the Angular components this blog uses in Markdown files.',
      });
    }

    if (true) {
      this.meta.addTag({
        name: 'keywords',
        content: 'blog,post,Angular,angular,nghost,_nghost,Markdown,md',
      });
    }
  }

  ngOnDestroy(): void {
    this.meta.removeTag('property="oh:title"');
    this.meta.removeTag('property="oh:type"');
    this.meta.removeTag('property="oh:url"');
    this.meta.removeTag('property="oh:image"');
    this.meta.removeTag('property="oh:image:secure_url"');

    if (true) {
      this.meta.removeTag('name=description');
    }

    if (true) {
      this.meta.removeTag('name=keywords');
    }
  }
}

@NgModule({
  imports: [
    CommonModule,
    RouterModule.forChild([
      {
        path: '',
        pathMatch: 'full',
        component: AngularComponentsInMarkdownComponent,
      },
    ]),
    CodeBlockComponent,
    CodeTabsComponent,
    DirectiveContextDemoComponent,
    HelloWorldComponent,
  ],
  declarations: [AngularComponentsInMarkdownComponent],
  bootstrap: [],
})
export class LazyModule {}
