// THIS FILE WAS GENERATED BY TOOLING. DO NOT EDIT THIS FILE DIRECTLY.

import {
  Component,
  NgModule,
  Inject,
  PLATFORM_ID,
  OnInit,
  OnDestroy,
} from '@angular/core';
import { RouterModule } from '@angular/router';
import { MarkdownModule } from 'ngx-markdown';
import { CommonModule } from '@angular/common';
import { isPlatformBrowser } from '@angular/common';
import { MarkdownService } from 'ngx-markdown';
import { Meta } from '@angular/platform-browser';

@Component({
  selector: 'blog-directive-context',
  template: `
    <markdown *ngIf="isBrowser" ngPreserveWhitespaces
      >You may recognize the usage of \`let isFirst = first\` in the following
      template \`\`\`html {{ '<' }}div *ngFor="let event of eventQueue; let
      isFirst = first"{{ '>' }} {{ '<' }}button *ngIf="isFirst"
      (click)="pop(event)"{{ '>' }}Execute Next Event{{ '<' }}/button{{ '>' }}
      {{ '<' }}h1{{ '>' }}{{ '{' }}{{ '{' }} event.name {{ '}' }}{{ '}'
      }}{{ '<' }}/h1{{ '>' }} {{ '<' }}/div{{ '>' }} \`\`\` It is a boolean
      variable exposed to the template supplied to the NgFor directive. It can
      be used to determine if the item rendering is the first item in the
      iterable passed into the directive. The example given is somewhat
      contrived but it should demonstrate clearly how the \`first\` variable is
      being used. You can read more on the
      [Angular.io](https://angular.io/api/common/NgForOf#local-variables) docs.
      The NgFor directive is not magical, it does not possess capabilites within
      it that are out of reach for any custom directives we may want to write
      ourselves. So then how do we do this? Where does the \`first\` variable
      come from? NgFor is a structural directive. This means that somewhere
      within the directive's logic, it changes the DOM layout by removing or
      creating DOM elements. In this case, NgFor creates embedded views based on
      the template we provide and the array passed in as an \`@Input\`. When
      this view is created, we have the option of exposing a context to that
      view. The NgFor directive provides a context object that contains a
      \`first\` get accessor. This is how we are able to use \`first\` in the
      NgFor template. Lets build a simple structural directive that renders the
      template provided to it and exposes a number to the created view that is
      randomly generated with \`Math.random()\` \`\`\`ts class
      RandomNumberContext {{ '{' }} constructor(public random: number) {{ '{'
      }}{{ '}' }}
      {{ '}' }}

      @Directive({{ '{' }}
      selector: "[appRandomNumber]",
      {{ '}' }}) export class RandomNumberDirective implements OnInit
      {{ '{' }} constructor( private _viewContainer: ViewContainerRef, private
      _templateRef: TemplateRef{{ '<' }}RandomNumberContext{{ '>' }} ) {{ '{'
      }}{{ '}' }}

      ngOnInit(): void {{ '{' }}
      // First arg is the template we passed in, second arg is a context that we
      can provide to the view this._viewContainer.createEmbeddedView(
      this._templateRef, new RandomNumberContext(Math.random()) );
      {{ '}' }}
      {{ '}' }}
      \`\`\` \`\`\`html
      {{ '<' }}p *appRandomNumber="let myRandomNumber = random"{{ '>' }} Your
      random num is: {{ '{' }}{{ '{' }} myRandomNumber {{ '}' }}{{ '}' }}
      {{ '<' }}/p{{ '>' }} \`\`\` Maybe we want to access our number as a
      percent. Lets expand our Context class in the following way, \`\`\`ts
      class RandomNumberContext {{ '{' }} constructor(public random: number)
      {{ '{' }}{{ '}' }}

      get asPercent(): string {{ '{' }}
      return (this.random * 100).toFixed(2) + "%";
      {{ '}' }}
      {{ '}' }}
      \`\`\` \`\`\`html
      {{ '<' }}p *appRandomNumber="let myRandomNumber = random; let
      myRandomPercentage = asPercent"
      {{ '>' }}
      Your random num is: {{ '{' }}{{ '{' }} myRandomNumber {{ '}' }}{{ '}' }},
      Your random percentage is: {{ '{' }}{{ '{' }} myRandomPercentage {{ '}'
      }}{{ '}' }} {{ '<' }}/p{{ '>' }}
      \`\`\`
    </markdown>
    <pre class="server-rendered" *ngIf="!isBrowser" [innerHtml]="content"></pre>
  `,
  styles: [
    `
      :host {
        display: block;
        max-width: 800px;
        margin: 2rem auto 0;

        @media screen and (max-width: 500px) {
          max-width: calc(100% - 24px);
        }
      }

      pre.server-rendered {
        all: unset;

        ::ng-deep {
          pre {
            background-color: #272822;
            padding: 12px;
            border-radius: 0.3rem;
            @media screen and (max-width: 500px) {
              margin: 0 -12px;
              border-radius: 0;
            }

            pre {
              padding: 1em;
              margin: 0.5em 0;
              overflow: auto;
              border-radius: 0.3em;
            }

            code[class*='language-'] {
              font-size: 0.9rem;
              color: #5ab9ca;
              background: none;
              text-shadow: 0 1px rgb(0 0 0 / 30%);
              text-align: left;
              white-space: pre;
              word-spacing: normal;
              word-break: normal;
              word-wrap: normal;
              line-height: 1.5;
              tab-size: 4;
              -webkit-hyphens: none;
              hyphens: none;
            }
          }
        }
      }
    `,
  ],
})
export class DirectiveContextComponent implements OnInit, OnDestroy {
  isBrowser = false;
  content = `You may recognize the usage of \`let isFirst = first\` in the following template

\`\`\`html
<div *ngFor="let event of eventQueue; let isFirst = first">
  <button *ngIf="isFirst" (click)="pop(event)">Execute Next Event</button>
  <h1>{{ event.name }}</h1>
</div>
\`\`\`

It is a boolean variable exposed to the template supplied to the NgFor directive. It can be used to determine if the item rendering is the first item in the iterable passed into the directive. The example given is somewhat contrived but it should demonstrate clearly how the \`first\` variable is being used. You can read more on the [Angular.io](https://angular.io/api/common/NgForOf#local-variables) docs.

The NgFor directive is not magical, it does not possess capabilites within it that are out of reach for any custom directives we may want to write ourselves. So then how do we do this? Where does the \`first\` variable come from?

NgFor is a structural directive. This means that somewhere within the directive's logic, it changes the DOM layout by removing or creating DOM elements. In this case, NgFor creates embedded views based on the template we provide and the array passed in as an \`@Input\`. When this view is created, we have the option of exposing a context to that view. The NgFor directive provides a context object that contains a \`first\` get accessor. This is how we are able to use \`first\` in the NgFor template.

Lets build a simple structural directive that renders the template provided to it and exposes a number to the created view that is randomly generated with \`Math.random()\`

\`\`\`ts
class RandomNumberContext {
  constructor(public random: number) {}
}

@Directive({
  selector: "[appRandomNumber]",
})
export class RandomNumberDirective implements OnInit {
  constructor(
    private _viewContainer: ViewContainerRef,
    private _templateRef: TemplateRef<RandomNumberContext>
  ) {}

  ngOnInit(): void {
    // First arg is the template we passed in, second arg is a context that we can provide to the view
    this._viewContainer.createEmbeddedView(
      this._templateRef,
      new RandomNumberContext(Math.random())
    );
  }
}
\`\`\`

\`\`\`html
<p *appRandomNumber="let myRandomNumber = random">
  Your random num is: {{ myRandomNumber }}
</p>
\`\`\`

Maybe we want to access our number as a percent. Lets expand our Context class in the following way,

\`\`\`ts
class RandomNumberContext {
  constructor(public random: number) {}

  get asPercent(): string {
    return (this.random * 100).toFixed(2) + "%";
  }
}
\`\`\`

\`\`\`html
<p
  *appRandomNumber="let myRandomNumber = random; let myRandomPercentage = asPercent"
>
  Your random num is: {{ myRandomNumber }}, Your random percentage is: {{
  myRandomPercentage }}
</p>
\`\`\`
`;

  constructor(
    @Inject(PLATFORM_ID) public platformId: Object,
    private markdownService: MarkdownService,
    private meta: Meta
  ) {}

  ngOnInit(): void {
    this.isBrowser = isPlatformBrowser(this.platformId);

    this.meta.addTag({ property: 'oh:title', content: 'Directive Context' });
    this.meta.addTag({ property: 'oh:type', content: 'article' });
    this.meta.addTag({
      property: 'oh:url',
      content:
        'https://aleksanderbodurri-eefbe.web.app/posts/directive-context',
    });
    this.meta.addTag({
      property: 'oh:image',
      content: 'http://aleksanderbodurri-eefbe.web.app/assets/me.png',
    });
    this.meta.addTag({
      property: 'oh:image:secure_url',
      content: 'https://aleksanderbodurri-eefbe.web.app/assets/me.png',
    });

    if (true) {
      this.meta.addTag({
        name: 'description',
        content: 'What is a directive context in Angular?',
      });
    }

    if (true) {
      this.meta.addTag({
        name: 'keywords',
        content:
          'blog,post,Angular,angular,angular directive,context,directive',
      });
    }

    if (!this.isBrowser) {
      this.content = this.markdownService.compile(this.content);
    }
  }

  ngOnDestroy(): void {
    this.meta.removeTag('property="oh:title"');
    this.meta.removeTag('property="oh:type"');
    this.meta.removeTag('property="oh:url"');
    this.meta.removeTag('property="oh:image"');
    this.meta.removeTag('property="oh:image:secure_url"');

    if (true) {
      this.meta.removeTag('name=description');
    }

    if (true) {
      this.meta.removeTag('name=keywords');
    }
  }
}

@NgModule({
  imports: [
    CommonModule,
    RouterModule.forChild([
      {
        path: '',
        pathMatch: 'full',
        component: DirectiveContextComponent,
      },
    ]),
    MarkdownModule.forChild(),
  ],
  declarations: [DirectiveContextComponent],
  bootstrap: [],
})
export class LazyModule {}
