// THIS FILE WAS GENERATED BY TOOLING. DO NOT EDIT THIS FILE DIRECTLY.

import { Component, NgModule, Inject, PLATFORM_ID } from '@angular/core';
import { RouterModule } from '@angular/router';
import { MarkdownModule } from 'ngx-markdown';
import { CommonModule } from '@angular/common';
import { isPlatformBrowser } from '@angular/common';
import { MarkdownService } from 'ngx-markdown';
import { Meta } from '@angular/platform-browser';

@Component({
  selector: 'blog-angular',
  template: `
    <markdown *ngIf="isBrowser" ngPreserveWhitespaces
      >{{ '<' }}h1 align="center"{{ '>' }}Angular - The modern web developer's
      platform.{{ '<' }}/h1{{ '>' }}

      {{ '<' }}p align="center"{{ '>' }} {{ '<' }}img
      src="https://raw.githubusercontent.com/angular/angular/main/aio/src/assets/images/logos/angular/angular.png"
      alt="angular-logo" width="120px" height="120px"/{{ '>' }} {{ '<' }}br{{
        '>'
      }}
      {{ '<' }}i{{ '>' }}Angular is a development platform for building mobile
      and desktop web applications {{ '<' }}br{{ '>' }} using
      Typescript/JavaScript and other languages.{{ '<' }}/i{{ '>' }}
      {{ '<' }}br{{ '>' }} {{ '<' }}/p{{ '>' }}

      {{ '<' }}p align="center"{{ '>' }} {{ '<' }}a
      href="https://www.angular.io"{{ '>' }}{{ '<' }}strong{{
        '>'
      }}www.angular.io{{ '<' }}/strong{{ '>' }}{{ '<' }}/a{{ '>' }}
      {{ '<' }}br{{ '>' }} {{ '<' }}/p{{ '>' }}

      {{ '<' }}p align="center"{{ '>' }} {{ '<' }}a href="CONTRIBUTING.md"{{
        '>'
      }}Contributing Guidelines{{ '<' }}/a{{ '>' }}
      ·
      {{ '<' }}a href="https://github.com/angular/angular/issues"{{ '>' }}Submit
      an Issue{{ '<' }}/a{{ '>' }}
      ·
      {{ '<' }}a href="https://blog.angular.io/"{{ '>' }}Blog{{ '<' }}/a{{
        '>'
      }}
      {{ '<' }}br{{ '>' }} {{ '<' }}br{{ '>' }} {{ '<' }}/p{{ '>' }}

      {{ '<' }}p align="center"{{ '>' }} {{ '<' }}a
      href="https://circleci.com/gh/angular/workflows/angular/tree/main"{{
        '>'
      }}
      {{ '<' }}img
      src="https://img.shields.io/circleci/build/github/angular/angular/main.svg?logo=circleci&logoColor=fff&label=CircleCI"
      alt="CI status" /{{ '>' }} {{ '<' }}/a{{ '>' }}&nbsp; {{ '<' }}a
      href="https://www.npmjs.com/@angular/core"{{ '>' }} {{ '<' }}img
      src="https://img.shields.io/npm/v/@angular/core.svg?logo=npm&logoColor=fff&label=NPM+package&color=limegreen"
      alt="Angular on npm" /{{ '>' }} {{ '<' }}/a{{ '>' }}&nbsp; {{ '<' }}a
      href="https://discord.gg/angular"{{ '>' }} {{ '<' }}img
      src="https://img.shields.io/discord/463752820026376202.svg?logo=discord&logoColor=fff&label=Discord&color=7389d8"
      alt="Discord conversation" /{{ '>' }} {{ '<' }}/a{{ '>' }} {{ '<' }}/p{{
        '>'
      }}

      {{ '<' }}hr{{ '>' }}

      ## Documentation Get started with Angular, learn the fundamentals and
      explore advanced topics on our documentation website. - [Getting
      Started][quickstart] - [Architecture][architecture] - [Components and
      Templates][componentstemplates] - [Forms][forms] - [API][api] ### Advanced
      - [Angular Elements][angularelements] - [Server Side Rendering][ssr] -
      [Schematics][schematics] - [Lazy Loading][lazyloading] -
      [Animations][animations] ## Development Setup ### Prerequisites - Install
      [Node.js] which includes [Node Package Manager][npm] ### Setting Up a
      Project Install the Angular CLI globally: \`\`\` npm install -g
      @angular/cli \`\`\` Create workspace: \`\`\` ng new [PROJECT NAME] \`\`\`
      Run the application: \`\`\` cd [PROJECT NAME] ng serve \`\`\` Angular is
      cross-platform, fast, scalable, has incredible tooling, and is loved by
      millions. ## Quickstart [Get started in 5 minutes][quickstart]. ##
      Ecosystem

      {{ '<' }}p{{ '>' }} {{ '<' }}img
      src="https://raw.githubusercontent.com/angular/angular/main/docs/images/angular-ecosystem-logos.png"
      alt="angular ecosystem logos" width="500px" height="auto"{{ '>' }}
      {{ '<' }}/p{{ '>' }}

      - [Angular Command Line (CLI)][cli] - [Angular Material][angularmaterial]
      ## Changelog [Learn about the latest improvements][changelog]. ##
      Upgrading Check out our [upgrade guide](https://update.angular.io/) to
      find out the best way to upgrade your project. ## Contributing ###
      Contributing Guidelines Read through our [contributing
      guidelines][contributing] to learn about our submission process, coding
      rules and more. ### Want to Help? Want to report a bug, contribute some
      code, or improve documentation? Excellent! Read up on our guidelines for
      [contributing][contributing] and then check out one of our issues labeled
      as {{ '<' }}kbd{{ '>' }}[help
      wanted](https://github.com/angular/angular/labels/help%20wanted){{
        '<'
      }}/kbd{{ '>' }} or {{ '<' }}kbd{{ '>' }}[good first
      issue](https://github.com/angular/angular/labels/good%20first%20issue){{
        '<'
      }}/kbd{{ '>' }}. ### Code of Conduct Help us keep Angular open and
      inclusive. Please read and follow our [Code of Conduct][codeofconduct]. ##
      Community Join the conversation and help the community. -
      [Twitter][twitter] - [Discord][discord] - [Gitter][gitter] -
      [YouTube][youtube] - [StackOverflow][stackoverflow] - Find a Local
      [Meetup][meetup] [![Love Angular
      badge](https://img.shields.io/badge/angular-love-blue?logo=angular&angular=love)](https://www.github.com/angular/angular)
      **Love Angular? Give our repo a star :star: :arrow_up:.** [contributing]:
      CONTRIBUTING.md [quickstart]: https://angular.io/start [changelog]:
      CHANGELOG.md [ng]: https://angular.io [documentation]:
      https://angular.io/docs [angularmaterial]: https://material.angular.io/
      [cli]: https://cli.angular.io/ [architecture]:
      https://angular.io/guide/architecture [componentstemplates]:
      https://angular.io/guide/displaying-data [forms]:
      https://angular.io/guide/forms-overview [api]: https://angular.io/api
      [angularelements]: https://angular.io/guide/elements [ssr]:
      https://angular.io/guide/universal [schematics]:
      https://angular.io/guide/schematics [lazyloading]:
      https://angular.io/guide/lazy-loading-ngmodules [node.js]:
      https://nodejs.org/ [npm]: https://www.npmjs.com/get-npm [codeofconduct]:
      CODE_OF_CONDUCT.md [twitter]: https://www.twitter.com/angular [discord]:
      https://discord.gg/angular [gitter]: https://gitter.im/angular/angular
      [stackoverflow]: https://stackoverflow.com/questions/tagged/angular
      [youtube]: https://youtube.com/angular [meetup]:
      https://www.meetup.com/find/?keywords=angular [animations]:
      https://angular.io/guide/animations
    </markdown>
    <pre class="server-rendered" *ngIf="!isBrowser" [innerHtml]="content"></pre>
  `,
  styles: [
    `
      :host {
        display: block;
        width: 70%;
        margin: 2rem auto 0;
      }

      pre.server-rendered {
        all: unset;

        ::ng-deep {
          pre {
            background-color: #1e1f21;
            padding: 12px;

            pre {
              padding: 1em;
              margin: 0.5em 0;
              overflow: auto;
              border-radius: 0.3em;
            }

            code[class*='language-'] {
              color: #5ab9ca;
            }
          }
        }
      }
    `,
  ],
})
export class AngularComponent {
  isBrowser = false;
  content = `<h1 align="center">Angular - The modern web developer's platform.</h1>

<p align="center">
  <img src="https://raw.githubusercontent.com/angular/angular/main/aio/src/assets/images/logos/angular/angular.png" alt="angular-logo" width="120px" height="120px"/>
  <br>
  <i>Angular is a development platform for building mobile and desktop web applications
    <br> using Typescript/JavaScript and other languages.</i>
  <br>
</p>

<p align="center">
  <a href="https://www.angular.io"><strong>www.angular.io</strong></a>
  <br>
</p>

<p align="center">
  <a href="CONTRIBUTING.md">Contributing Guidelines</a>
  ·
  <a href="https://github.com/angular/angular/issues">Submit an Issue</a>
  ·
  <a href="https://blog.angular.io/">Blog</a>
  <br>
  <br>
</p>

<p align="center">
  <a href="https://circleci.com/gh/angular/workflows/angular/tree/main">
    <img src="https://img.shields.io/circleci/build/github/angular/angular/main.svg?logo=circleci&logoColor=fff&label=CircleCI" alt="CI status" />
  </a>&nbsp;
  <a href="https://www.npmjs.com/@angular/core">
    <img src="https://img.shields.io/npm/v/@angular/core.svg?logo=npm&logoColor=fff&label=NPM+package&color=limegreen" alt="Angular on npm" />
  </a>&nbsp;
  <a href="https://discord.gg/angular">
    <img src="https://img.shields.io/discord/463752820026376202.svg?logo=discord&logoColor=fff&label=Discord&color=7389d8" alt="Discord conversation" />
  </a>
</p>

<hr>

## Documentation

Get started with Angular, learn the fundamentals and explore advanced topics on our documentation website.

- [Getting Started][quickstart]
- [Architecture][architecture]
- [Components and Templates][componentstemplates]
- [Forms][forms]
- [API][api]

### Advanced

- [Angular Elements][angularelements]
- [Server Side Rendering][ssr]
- [Schematics][schematics]
- [Lazy Loading][lazyloading]
- [Animations][animations]

## Development Setup

### Prerequisites

- Install [Node.js] which includes [Node Package Manager][npm]

### Setting Up a Project

Install the Angular CLI globally:

\`\`\`
npm install -g @angular/cli
\`\`\`

Create workspace:

\`\`\`
ng new [PROJECT NAME]
\`\`\`

Run the application:

\`\`\`
cd [PROJECT NAME]
ng serve
\`\`\`

Angular is cross-platform, fast, scalable, has incredible tooling, and is loved by millions.

## Quickstart

[Get started in 5 minutes][quickstart].

## Ecosystem

<p>
  <img src="https://raw.githubusercontent.com/angular/angular/main/docs/images/angular-ecosystem-logos.png" alt="angular ecosystem logos" width="500px" height="auto">
</p>

- [Angular Command Line (CLI)][cli]
- [Angular Material][angularmaterial]

## Changelog

[Learn about the latest improvements][changelog].

## Upgrading

Check out our [upgrade guide](https://update.angular.io/) to find out the best way to upgrade your project.

## Contributing

### Contributing Guidelines

Read through our [contributing guidelines][contributing] to learn about our submission process, coding rules and more.

### Want to Help?

Want to report a bug, contribute some code, or improve documentation? Excellent! Read up on our guidelines for [contributing][contributing] and then check out one of our issues labeled as <kbd>[help wanted](https://github.com/angular/angular/labels/help%20wanted)</kbd> or <kbd>[good first issue](https://github.com/angular/angular/labels/good%20first%20issue)</kbd>.

### Code of Conduct

Help us keep Angular open and inclusive. Please read and follow our [Code of Conduct][codeofconduct].

## Community

Join the conversation and help the community.

- [Twitter][twitter]
- [Discord][discord]
- [Gitter][gitter]
- [YouTube][youtube]
- [StackOverflow][stackoverflow]
- Find a Local [Meetup][meetup]

[![Love Angular badge](https://img.shields.io/badge/angular-love-blue?logo=angular&angular=love)](https://www.github.com/angular/angular)

**Love Angular? Give our repo a star :star: :arrow_up:.**

[contributing]: CONTRIBUTING.md
[quickstart]: https://angular.io/start
[changelog]: CHANGELOG.md
[ng]: https://angular.io
[documentation]: https://angular.io/docs
[angularmaterial]: https://material.angular.io/
[cli]: https://cli.angular.io/
[architecture]: https://angular.io/guide/architecture
[componentstemplates]: https://angular.io/guide/displaying-data
[forms]: https://angular.io/guide/forms-overview
[api]: https://angular.io/api
[angularelements]: https://angular.io/guide/elements
[ssr]: https://angular.io/guide/universal
[schematics]: https://angular.io/guide/schematics
[lazyloading]: https://angular.io/guide/lazy-loading-ngmodules
[node.js]: https://nodejs.org/
[npm]: https://www.npmjs.com/get-npm
[codeofconduct]: CODE_OF_CONDUCT.md
[twitter]: https://www.twitter.com/angular
[discord]: https://discord.gg/angular
[gitter]: https://gitter.im/angular/angular
[stackoverflow]: https://stackoverflow.com/questions/tagged/angular
[youtube]: https://youtube.com/angular
[meetup]: https://www.meetup.com/find/?keywords=angular
[animations]: https://angular.io/guide/animations
`;

  constructor(
    @Inject(PLATFORM_ID) platformId: Object,
    private markdownService: MarkdownService,
    private meta: Meta
  ) {
    this.isBrowser = isPlatformBrowser(platformId);

    if (true) {
      this.meta.addTag({ name: 'description', content: 'Angular is cool.' });
    }

    if (true) {
      this.meta.addTag({ name: 'keywords', content: 'Angular' });
    }

    if (!this.isBrowser) {
      this.content = this.markdownService.compile(this.content);
    }
  }
}

@NgModule({
  imports: [
    CommonModule,
    RouterModule.forChild([
      {
        path: '',
        pathMatch: 'full',
        component: AngularComponent,
      },
    ]),
    MarkdownModule.forChild(),
  ],
  declarations: [AngularComponent],
  bootstrap: [],
})
export class LazyModule {}
